### ISSUE TITLE
Some apps disable greyscale

### ISSUE THREAD

**Issue by mayeaux** [rkbhochalya/grayscale-mode#9] opened 2021-09-01 01:11 UTC
Great app, sorely missed. However, I notice some things turn off the grayscale effect, such as either closing or opening the app LaunchControl.app

Anybody else experienced this? What's causing it and what's a fix? Thanks!

Update: Also happens with Telegram, I'll keep updating as I try and figure out what's going on here.

Also, after the app closes or opens, the first time I do the keyboard shortcut it doesn't work, I have to do it twice 🤔

**Comment by mayeaux** [comment] 2021-09-01 01:52
In fact, grayscale doesn't stay on for more than like 15 minutes at a time. And it's not from the app per se because I know it happens with this c script that I have as well, something somwhere is turning the greyscale off 🤔

**Comment by mayeaux** [comment] 2021-09-01 02:27
Opening/minimizing Skype has the same effect. Wonder what's going on.

**Comment by jvican** [comment] 2021-10-12 21:23
Weird, I'm not having this issue with Telegram on macOS Big Sur 11.6

**Comment by rkbhochalya** [comment] 2021-11-11 11:12
@jvican thanks for the update.

**Comment by rkbhochalya** [comment] 2021-11-11 11:13
@mayeaux I'm closing it as I'm unable to reproduce this issue macOS Big Sur 11.6 and macOS Monterey 12.0. Also, it doesn't seem to be related to the app specifically as you said it happens with the C script you are using.

**Closed by rkbhochalya** 2021-11-11 11:13 UTC

**Comment by mayeaux** [comment] 2021-11-17 05:15
Yeah I wonder, given this code:

```
// clang -g -O2 -std=c11 -Wall -framework ApplicationServices
// https://stackoverflow.com/questions/14163788/how-does-on-screen-color-inversion-work-in-os-x
#include <stdio.h>
#include <ApplicationServices/ApplicationServices.h>

CG_EXTERN bool CGDisplayUsesForceToGray(void);
CG_EXTERN void CGDisplayForceToGray(bool forceToGray);

int
main(int argc, char** argv)
{
    bool isGrayscale = CGDisplayUsesForceToGray();
    printf("isGrayscale = %d\n", isGrayscale);
    // switch to grayscale if it's not on
    if(isGrayscale == 0){
        CGDisplayForceToGray(true);
    // already turned on, dont need to do anything
    } else {
        printf("No need to turn gray\n");
    }
    printf("Grayscale is now: %d\n", CGDisplayUsesForceToGray());

    return 0;
}
```

I can use the keyboard shortcut of your app to toggle colour on and off, and then leave it on. Yet I run this script above, and it says grayscale is on, but the colour is still there (and is only finally turned grayscale when I use the keyboard shortcut from your app again). I don't know much system coding so I'm a bit confused as to what's happening here, it's like there is different state being saved, or something. 🤔  Does anything jump out to you as an obvious cause? Btw thanks, love the app!

**Comment by mayeaux** [comment] 2021-11-17 05:24
Not a big priority though as I found a workaround: turn the grayscale off and then back on again. This fixes the issue of my script thinking grayscale is activated while there is still colour (because the colour was turned on using the keyboard shortcut of your app). So not sure what's going on there but my workaround is working fine so no worries really.
